### ISSUE TITLE
All links on footer don't work

### ISSUE THREAD

**Issue by romaricsylvain** [scaf-cheick/debuglinks#2]
Hello ! Maybe we must create new pages for other link , such as best contributors ,top post,etc.
It don't work actually
![image](https://user-images.githubusercontent.com/56646072/147099669-148b6044-db06-4efa-82e4-23ab66e8750e.png)

**Comment by scaf-cheick** [comment]
Great. Good idea. 
I take care of it

**Comment by romaricsylvain** [comment]
I close this. Problem is resolved
